// Demo list. Tickers are 1-5 letters, matching the format the chat assistant recognizes.
const COMPANY_ROWS = [
  ["Abbott Laboratories", "ABT"],
  ["AT&T", "T"],
  ["Boeing", "BA"],
  ["Citigroup", "C"],
  ["Coca-Cola", "KO"],
  ["Ford Motor", "F"],
  ["General Electric", "GE"],
  ["General Motors", "GM"],
  ["Mastercard", "MA"],
  ["Micron Technology", "MU"],
  ["Procter & Gamble", "PG"],
  ["Verizon", "VZ"],
  ["Visa", "V"],
  ["AbbVie", "ABBV"],
  ["Accenture", "ACN"],
  ["Adobe", "ADBE"],
  ["Advanced Micro Devices", "AMD"],
  ["Aflac", "AFL"],
  ["Air Products and Chemicals", "APD"],
  ["Airbnb", "ABNB"],
  ["Alphabet (Google)", "GOOG"],
  ["Amazon.com", "AMZN"],
  ["American Express", "AXP"],
  ["American Tower", "AMT"],
  ["Amgen", "AMGN"],
  ["Amphenol", "APH"],
  ["Analog Devices", "ADI"],
  ["Aon", "AON"],
  ["Apple", "AAPL"],
  ["Applied Materials", "AMAT"],
  ["Archer-Daniels-Midland", "ADM"],
  ["Arista Networks", "ANET"],
  ["Arthur J. Gallagher", "AJG"],
  ["Autodesk", "ADSK"],
  ["Automatic Data Processing", "ADP"],
  ["AutoZone", "AZO"],
  ["Bank of America", "BAC"],
  ["Becton Dickinson", "BDX"],
  ["Best Buy", "BBY"],
  ["Biogen", "BIIB"],
  ["BlackRock", "BLK"],
  ["Booking Holdings", "BKNG"],
  ["Boston Scientific", "BSX"],
  ["Bristol-Myers Squibb", "BMY"],
  ["Broadcom", "AVGO"],
  ["Cadence Design Systems", "CDNS"],
  ["Capital One Financial", "COF"],
  ["Cardinal Health", "CAH"],
  ["Carrier Global", "CARR"],
  ["Caterpillar", "CAT"],
  ["CBRE Group", "CBRE"],
  ["Charles Schwab", "SCHW"],
  ["Charter Communications", "CHTR"],
  ["Chevron", "CVX"],
  ["Chipotle Mexican Grill", "CMG"],
  ["Cisco Systems", "CSCO"],
  ["CME Group", "CME"],
  ["Cognizant Technology Solutions", "CTSH"],
  ["ConocoPhillips", "COP"],
  ["Constellation Brands", "STZ"],
  ["Constellation Energy", "CEG"],
  ["Costco Wholesale", "COST"],
  ["CrowdStrike", "CRWD"],
  ["CSX Corporation", "CSX"],
  ["Cummins", "CMI"],
  ["CVS Health", "CVS"],
  ["Danaher", "DHR"],
  ["Darden Restaurants", "DRI"],
  ["Dell Technologies", "DELL"],
  ["Delta Air Lines", "DAL"],
  ["Dexcom", "DXCM"],
  ["Diamondback Energy", "FANG"],
  ["Digital Realty", "DLR"],
  ["Dollar Tree", "DLTR"],
  ["DoorDash", "DASH"],
  ["Dow", "DOW"],
  ["Duke Energy", "DUK"],
  ["eBay", "EBAY"],
  ["Ecolab", "ECL"],
  ["Elevance Health", "ELV"],
  ["Eli Lilly", "LLY"],
  ["Emerson Electric", "EMR"],
  ["EOG Resources", "EOG"],
  ["Equifax", "EFX"],
  ["Equinix", "EQIX"],
  ["Exelon", "EXC"],
  ["Expedia Group", "EXPE"],
  ["Exxon Mobil", "XOM"],
  ["FedEx", "FDX"],
  ["First Solar", "FSLR"],
  ["Fortinet", "FTNT"],
  ["Fox Corporation", "FOXA"],
  ["Freeport-McMoRan", "FCX"],
  ["Garmin", "GRMN"],
  ["GE HealthCare", "GEHC"],
  ["GE Vernova", "GEV"],
  ["General Mills", "GIS"],
  ["Gilead Sciences", "GILD"],
  ["Halliburton", "HAL"],
  ["Hershey", "HSY"],
  ["Hewlett Packard Enterprise", "HPE"],
  ["Hilton Worldwide", "HLT"],
  ["Honeywell", "HON"],
  ["HP Inc.", "HPQ"],
  ["Humana", "HUM"],
  ["IBM", "IBM"],
  ["IDEXX Laboratories", "IDXX"],
  ["Illinois Tool Works", "ITW"],
  ["Intel", "INTC"],
  ["Intercontinental Exchange", "ICE"],
  ["Intuit", "INTU"],
  ["Intuitive Surgical", "ISRG"],
  ["IQVIA", "IQV"],
  ["IREN", "IREN"],
  ["Johnson & Johnson", "JNJ"],
  ["Johnson Controls", "JCI"],
  ["JPMorgan Chase", "JPM"],
  ["Keurig Dr Pepper", "KDP"],
  ["Kimberly-Clark", "KMB"],
  ["Kinder Morgan", "KMI"],
  ["KLA Corporation", "KLAC"],
  ["Kraft Heinz", "KHC"],
  ["L3Harris Technologies", "LHX"],
  ["Lam Research", "LRCX"],
  ["Las Vegas Sands", "LVS"],
  ["Lennar", "LEN"],
  ["Lockheed Martin", "LMT"],
  ["Lowe's", "LOW"],
  ["Lululemon Athletica", "LULU"],
  ["Marathon Petroleum", "MPC"],
  ["Marriott International", "MAR"],
  ["McCormick", "MKC"],
  ["McDonald's", "MCD"],
  ["McKesson", "MCK"],
  ["Medtronic", "MDT"],
  ["Merck", "MRK"],
  ["Meta Platforms", "META"],
  ["MetLife", "MET"],
  ["Microchip Technology", "MCHP"],
  ["Microsoft", "MSFT"],
  ["Moderna", "MRNA"],
  ["Mondelez International", "MDLZ"],
  ["Monster Beverage", "MNST"],
  ["Moody's", "MCO"],
  ["Motorola Solutions", "MSI"],
  ["MSCI", "MSCI"],
  ["Netflix", "NFLX"],
  ["Newmont", "NEM"],
  ["NextEra Energy", "NEE"],
  ["Nike", "NKE"],
  ["Northrop Grumman", "NOC"],
  ["Nucor", "NUE"],
  ["NVIDIA", "NVDA"],
  ["NXP Semiconductors", "NXPI"],
  ["Occidental Petroleum", "OXY"],
  ["Old Dominion Freight Line", "ODFL"],
  ["Oracle", "ORCL"],
  ["O'Reilly Automotive", "ORLY"],
  ["Palantir Technologies", "PLTR"],
  ["Palo Alto Networks", "PANW"],
  ["Paychex", "PAYX"],
  ["PayPal", "PYPL"],
  ["PepsiCo", "PEP"],
  ["Pfizer", "PFE"],
  ["Phillips 66", "PSX"],
  ["PNC Financial Services", "PNC"],
  ["PPG Industries", "PPG"],
  ["Progressive", "PGR"],
  ["Prologis", "PLD"],
  ["Prudential Financial", "PRU"],
  ["Public Storage", "PSA"],
  ["Qualcomm", "QCOM"],
  ["Quanta Services", "PWR"],
  ["Regeneron Pharmaceuticals", "REGN"],
  ["Republic Services", "RSG"],
  ["ResMed", "RMD"],
  ["Ross Stores", "ROST"],
  ["RTX Corporation", "RTX"],
  ["S&P Global", "SPGI"],
  ["Salesforce", "CRM"],
  ["ServiceNow", "NOW"],
  ["Sherwin-Williams", "SHW"],
  ["Simon Property Group", "SPG"],
  ["Southwest Airlines", "LUV"],
  ["Starbucks", "SBUX"],
  ["Stryker", "SYK"],
  ["Synopsys", "SNPS"],
  ["Sysco", "SYY"],
  ["T-Mobile US", "TMUS"],
  ["Target", "TGT"],
  ["Tesla", "TSLA"],
  ["Texas Instruments", "TXN"],
  ["Thermo Fisher Scientific", "TMO"],
  ["TJX Companies", "TJX"],
  ["Travelers", "TRV"],
  ["Truist Financial", "TFC"],
  ["Uber Technologies", "UBER"],
  ["Union Pacific", "UNP"],
  ["United Airlines", "UAL"],
  ["United Parcel Service", "UPS"],
  ["UnitedHealth Group", "UNH"],
  ["U.S. Bancorp", "USB"],
  ["Valero Energy", "VLO"],
  ["Vertex Pharmaceuticals", "VRTX"],
  ["Walmart", "WMT"],
  ["Walt Disney", "DIS"],
  ["Wells Fargo", "WFC"],
  ["Welltower", "WELL"],
  ["Workday", "WDAY"],
  ["Xcel Energy", "XEL"],
  ["Yum! Brands", "YUM"],
  ["Zoetis", "ZTS"],
];

export const COMPANIES = COMPANY_ROWS.map(([name, ticker]) => ({ name, ticker })).sort((a, b) =>
  a.name.localeCompare(b.name, "en", { sensitivity: "base" }),
);
